use_frameworks!

platform :ios, '10.0'

target 'ChainControl_Example' do
  pod 'ChainControl', :path => '../'

  target 'ChainControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
